version: "3"

services:
  webapp-main:
    image: wordpress:latest
    container_name: webapp-main
    restart: always
    expose:
       - 80
    environment:
      VIRTUAL_HOST: bapuhome.net
      WORDPRESS_DB_HOST: webcore-db:3306
      WORDPRESS_DB_USER: bapuuser
      WORDPRESS_DB_PASSWORD: bapuuser
      WORDPRESS_DB_NAME: bapuhome
    networks:
      - webapp-net

networks:
  webapp-net:
    external:
      name: webcore-stack_webcore-net