version: "3"

services:
  webapp-main:
    image: wordpress:latest
    container_name: webapp-main
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: bapuhome.net
      WORDPRESS_DB_HOST: webcore-db:3306
      WORDPRESS_DB_USER: bapuuser
      WORDPRESS_DB_PASSWORD: bapuuser
      WORDPRESS_DB_NAME: bapuhome
    volumes:
      - /docker-files/webapps/bapuhome:/var/www/html
    networks:
      - webapp-net

  webapp-dev-php7:
    image: nginx:latest
    container_name: webapp-dev-php7
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dev-php7.bapuhome.net
    volumes:
      - /web-files/dev-php7:/web-files
      - /docker-files/webapps/dev-php7/nginx-config/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - webapp-net

  php7-fpm:
    image: php:7-fpm
    volumes:
      - /web-files/dev-php7:/web-files
    networks:
      - webapp-net

networks:
  webapp-net:
    external:
      name: webcore-stack_webcore-net