version: "3"

services:
  phpipam-web:
    image: rafpe/docker-phpipam
    container_name: phpipam-web
    restart: unless-stopped
    ports:
      - 8880:80
    environment:
      - MYSQL_DB_HOSTNAME=phpipam-db
      - MYSQL_DB_USERNAME=phpipam
      - MYSQL_DB_PASSWORD=phpipam
      - MYSQL_DB_NAME=phpipam
      - MYSQL_DB_PORT=3306
    volumes:
      - /docker-files/phpipam/www/phpipam-logo:/phpipam/css/images/logo
    depends_on:
      - phpipam-db
    networks:
      - ipam-net

  phpipam-db:
    image: linuxserver/mariadb:latest
    container_name: phpipam-db
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=phpipam
    volumes:
      - /docker-files/phpipam/db:/var/lib/mysql
    networks:
      - ipam-net

networks:
  ipam-net:
    driver: bridge