version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: dns-pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      - TZ=Asia/Jakarta
      - WEBPASSWORD=welcome1
      - DNS1='cloudflared#5054'
      - DNS2=''
    volumes:
      - '/docker-files/pihole/etc-pihole/:/etc/pihole/'
      - '/docker-files/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      - dns-net 
    cap_add:
      - NET_ADMIN

  cloudflared:
    image: visibilityspots/cloudflared:latest
    container_name: dns-cloudflared
    restart: unless-stopped
    expose:
      - 5054
    networks:
      - dns-net

networks:
  dns-net:
    driver: bridge