version: "2.1"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - MENU_VERSION=1.9.9
      - PORT_RANGE=30000:30010
    volumes:
      - /docker-files/pxeserver/config:/config
      - /docker-files/pxeserver/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped