version: "3"

services:
  mktxp:
    image: guenterbailey/mktxp:latest
    restart: on-failure
    container_name: mktxp
    volumes:
      - /docker-files/mktxp/config:/root/mktxp:rw
    ports:
      - "49090:49090"