version: "3"

services:
  openproject:
    image: openproject/community:11
    container_name: openproject
    restart: unless-stopped
    ports:
      - "8881:53/tcp"
    environment:
      - SECRET_KEY_BASE=welcome1
      - SERVER_HOSTNAME=op.bapuhome.net
    volumes:
      - '/docker-files/openproject/pgdata:/var/openproject/pgdata'
      - '/docker-files/openproject/assets/:/var/openproject/assets'