version: '3'
services:
  webcore-proxy:
    image: jwilder/nginx-proxy
    container_name: webcore-proxy
    restart: unless-stopped
    ports:
      - "8880:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webcore-net

  webcore-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: webcore-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: welcome1
      SERVICE_NAME: mysql
    volumes:
      - /docker-files/webcore/mysql:/var/lib/mysql
    networks:
      - webcore-net

  webcore-pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: webcore-pma
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: pma.bapuhome.net
      PMA_HOST: webcore-db
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: welcome1
    depends_on:
      - webcore-db
    networks:
      - webcore-net

networks:
  webcore-net:
    driver: bridge