version: '3'

services:
  stepca-stack:
    image: smallstep/step-ca
    restart: unless-stopped
    container_name: step-ca
    ports:
      - "9000:9000"
    volumes:
      - /docker-files/step-ca/step:/home/step