version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      # These are the settings to access your db
      #DB_MYSQL_HOST: "db"
      #DB_MYSQL_PORT: 3306
      #DB_MYSQL_USER: "npm"
      #DB_MYSQL_PASSWORD: "welcome1"
      #DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - /docker-files/npm/data:/data
      - /docker-files/npm/letsencrypt:/etc/letsencrypt
    #depends_on:
    #  - db
  #db:
    #image: 'jc21/mariadb-aria:latest'
    #restart: unless-stopped
    #environment:
      #MYSQL_ROOT_PASSWORD: 'welcome1'
      #MYSQL_DATABASE: 'npm'
      #MYSQL_USER: 'npm'
      #MYSQL_PASSWORD: 'welcome1'
    #volumes:
      #- /docker/docker-config/npm/data/mysql:/var/lib/mysql